// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.0
// source: advanced/payment.proto

package advpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Payment_Status int32

const (
	Payment_STATUS_UNSPECIFIED Payment_Status = 0 // 零值必须是"未指定"，不要赋予业务含义
	Payment_STATUS_PAID        Payment_Status = 1
	Payment_STATUS_REFUNDED    Payment_Status = 2
)

// Enum value maps for Payment_Status.
var (
	Payment_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_PAID",
		2: "STATUS_REFUNDED",
	}
	Payment_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_PAID":        1,
		"STATUS_REFUNDED":    2,
	}
)

func (x Payment_Status) Enum() *Payment_Status {
	p := new(Payment_Status)
	*p = x
	return p
}

func (x Payment_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Payment_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_advanced_payment_proto_enumTypes[0].Descriptor()
}

func (Payment_Status) Type() protoreflect.EnumType {
	return &file_advanced_payment_proto_enumTypes[0]
}

func (x Payment_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Payment_Status.Descriptor instead.
func (Payment_Status) EnumDescriptor() ([]byte, []int) {
	return file_advanced_payment_proto_rawDescGZIP(), []int{0, 0}
}

// Payment 演示高级类型：oneof、optional、Timestamp、嵌套消息、枚举、map
type Payment struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	OrderId     string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	AmountCents int64                  `protobuf:"varint,2,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	PaidAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	Status      Payment_Status         `protobuf:"varint,4,opt,name=status,proto3,enum=advanced.Payment_Status" json:"status,omitempty"`
	// method 是 oneof：同一时刻只有一个字段被设置，天然表达"二选一/多选一"
	//
	// Types that are valid to be assigned to Method:
	//
	//	*Payment_PayCard
	//	*Payment_PayWechat
	//	*Payment_PayPoints
	Method isPayment_Method `protobuf_oneof:"method"`
	// remark 用 optional：可以区分"没传"和"传了空字符串"
	Remark *string `protobuf:"bytes,8,opt,name=remark,proto3,oneof" json:"remark,omitempty"`
	// 扩展字段用 map，比重复的 key/value 消息更直接
	Metadata      map[string]string `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_advanced_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_advanced_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_advanced_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Payment) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *Payment) GetPaidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

func (x *Payment) GetStatus() Payment_Status {
	if x != nil {
		return x.Status
	}
	return Payment_STATUS_UNSPECIFIED
}

func (x *Payment) GetMethod() isPayment_Method {
	if x != nil {
		return x.Method
	}
	return nil
}

func (x *Payment) GetPayCard() *Payment_Card {
	if x != nil {
		if x, ok := x.Method.(*Payment_PayCard); ok {
			return x.PayCard
		}
	}
	return nil
}

func (x *Payment) GetPayWechat() *Payment_WeChat {
	if x != nil {
		if x, ok := x.Method.(*Payment_PayWechat); ok {
			return x.PayWechat
		}
	}
	return nil
}

func (x *Payment) GetPayPoints() *Payment_Points {
	if x != nil {
		if x, ok := x.Method.(*Payment_PayPoints); ok {
			return x.PayPoints
		}
	}
	return nil
}

func (x *Payment) GetRemark() string {
	if x != nil && x.Remark != nil {
		return *x.Remark
	}
	return ""
}

func (x *Payment) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type isPayment_Method interface {
	isPayment_Method()
}

type Payment_PayCard struct {
	PayCard *Payment_Card `protobuf:"bytes,5,opt,name=pay_card,json=payCard,proto3,oneof"`
}

type Payment_PayWechat struct {
	PayWechat *Payment_WeChat `protobuf:"bytes,6,opt,name=pay_wechat,json=payWechat,proto3,oneof"`
}

type Payment_PayPoints struct {
	PayPoints *Payment_Points `protobuf:"bytes,7,opt,name=pay_points,json=payPoints,proto3,oneof"`
}

func (*Payment_PayCard) isPayment_Method() {}

func (*Payment_PayWechat) isPayment_Method() {}

func (*Payment_PayPoints) isPayment_Method() {}

type Payment_Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Last4         string                 `protobuf:"bytes,1,opt,name=last4,proto3" json:"last4,omitempty"`
	Brand         string                 `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment_Card) Reset() {
	*x = Payment_Card{}
	mi := &file_advanced_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment_Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment_Card) ProtoMessage() {}

func (x *Payment_Card) ProtoReflect() protoreflect.Message {
	mi := &file_advanced_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment_Card.ProtoReflect.Descriptor instead.
func (*Payment_Card) Descriptor() ([]byte, []int) {
	return file_advanced_payment_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Payment_Card) GetLast4() string {
	if x != nil {
		return x.Last4
	}
	return ""
}

func (x *Payment_Card) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

type Payment_WeChat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment_WeChat) Reset() {
	*x = Payment_WeChat{}
	mi := &file_advanced_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment_WeChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment_WeChat) ProtoMessage() {}

func (x *Payment_WeChat) ProtoReflect() protoreflect.Message {
	mi := &file_advanced_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment_WeChat.ProtoReflect.Descriptor instead.
func (*Payment_WeChat) Descriptor() ([]byte, []int) {
	return file_advanced_payment_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Payment_WeChat) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type Payment_Points struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PointsUsed    int64                  `protobuf:"varint,1,opt,name=points_used,json=pointsUsed,proto3" json:"points_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment_Points) Reset() {
	*x = Payment_Points{}
	mi := &file_advanced_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment_Points) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment_Points) ProtoMessage() {}

func (x *Payment_Points) ProtoReflect() protoreflect.Message {
	mi := &file_advanced_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment_Points.ProtoReflect.Descriptor instead.
func (*Payment_Points) Descriptor() ([]byte, []int) {
	return file_advanced_payment_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Payment_Points) GetPointsUsed() int64 {
	if x != nil {
		return x.PointsUsed
	}
	return 0
}

var File_advanced_payment_proto protoreflect.FileDescriptor

const file_advanced_payment_proto_rawDesc = "" +
	"\n" +
	"\x16advanced/payment.proto\x12\badvanced\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdd\x05\n" +
	"\aPayment\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12!\n" +
	"\famount_cents\x18\x02 \x01(\x03R\vamountCents\x123\n" +
	"\apaid_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06paidAt\x120\n" +
	"\x06status\x18\x04 \x01(\x0e2\x18.advanced.Payment.StatusR\x06status\x123\n" +
	"\bpay_card\x18\x05 \x01(\v2\x16.advanced.Payment.CardH\x00R\apayCard\x129\n" +
	"\n" +
	"pay_wechat\x18\x06 \x01(\v2\x18.advanced.Payment.WeChatH\x00R\tpayWechat\x129\n" +
	"\n" +
	"pay_points\x18\a \x01(\v2\x18.advanced.Payment.PointsH\x00R\tpayPoints\x12\x1b\n" +
	"\x06remark\x18\b \x01(\tH\x01R\x06remark\x88\x01\x01\x12;\n" +
	"\bmetadata\x18\t \x03(\v2\x1f.advanced.Payment.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a2\n" +
	"\x04Card\x12\x14\n" +
	"\x05last4\x18\x01 \x01(\tR\x05last4\x12\x14\n" +
	"\x05brand\x18\x02 \x01(\tR\x05brand\x1a/\n" +
	"\x06WeChat\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x1a)\n" +
	"\x06Points\x12\x1f\n" +
	"\vpoints_used\x18\x01 \x01(\x03R\n" +
	"pointsUsed\"F\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vSTATUS_PAID\x10\x01\x12\x13\n" +
	"\x0fSTATUS_REFUNDED\x10\x02B\b\n" +
	"\x06methodB\t\n" +
	"\a_remarkB2Z0github.com/go-book/protobuf/proto/advanced;advpbb\x06proto3"

var (
	file_advanced_payment_proto_rawDescOnce sync.Once
	file_advanced_payment_proto_rawDescData []byte
)

func file_advanced_payment_proto_rawDescGZIP() []byte {
	file_advanced_payment_proto_rawDescOnce.Do(func() {
		file_advanced_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_advanced_payment_proto_rawDesc), len(file_advanced_payment_proto_rawDesc)))
	})
	return file_advanced_payment_proto_rawDescData
}

var file_advanced_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_advanced_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_advanced_payment_proto_goTypes = []any{
	(Payment_Status)(0),           // 0: advanced.Payment.Status
	(*Payment)(nil),               // 1: advanced.Payment
	nil,                           // 2: advanced.Payment.MetadataEntry
	(*Payment_Card)(nil),          // 3: advanced.Payment.Card
	(*Payment_WeChat)(nil),        // 4: advanced.Payment.WeChat
	(*Payment_Points)(nil),        // 5: advanced.Payment.Points
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_advanced_payment_proto_depIdxs = []int32{
	6, // 0: advanced.Payment.paid_at:type_name -> google.protobuf.Timestamp
	0, // 1: advanced.Payment.status:type_name -> advanced.Payment.Status
	3, // 2: advanced.Payment.pay_card:type_name -> advanced.Payment.Card
	4, // 3: advanced.Payment.pay_wechat:type_name -> advanced.Payment.WeChat
	5, // 4: advanced.Payment.pay_points:type_name -> advanced.Payment.Points
	2, // 5: advanced.Payment.metadata:type_name -> advanced.Payment.MetadataEntry
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_advanced_payment_proto_init() }
func file_advanced_payment_proto_init() {
	if File_advanced_payment_proto != nil {
		return
	}
	file_advanced_payment_proto_msgTypes[0].OneofWrappers = []any{
		(*Payment_PayCard)(nil),
		(*Payment_PayWechat)(nil),
		(*Payment_PayPoints)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_advanced_payment_proto_rawDesc), len(file_advanced_payment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_advanced_payment_proto_goTypes,
		DependencyIndexes: file_advanced_payment_proto_depIdxs,
		EnumInfos:         file_advanced_payment_proto_enumTypes,
		MessageInfos:      file_advanced_payment_proto_msgTypes,
	}.Build()
	File_advanced_payment_proto = out.File
	file_advanced_payment_proto_goTypes = nil
	file_advanced_payment_proto_depIdxs = nil
}
