// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.0
// source: evolve/v1/event.proto

package evolvev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event 是事件契约的 v1 版本。
// 演进到 v2 时：新增 channel，废弃 source。
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Ts            int64                  `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"` // v2 中废弃，用 channel 替代
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_evolve_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_evolve_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_evolve_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_evolve_v1_event_proto protoreflect.FileDescriptor

const file_evolve_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x15evolve/v1/event.proto\x12\tevolve.v1\"S\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\x03R\x02ts\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06sourceB6Z4github.com/go-book/protobuf/proto/evolve/v1;evolvev1b\x06proto3"

var (
	file_evolve_v1_event_proto_rawDescOnce sync.Once
	file_evolve_v1_event_proto_rawDescData []byte
)

func file_evolve_v1_event_proto_rawDescGZIP() []byte {
	file_evolve_v1_event_proto_rawDescOnce.Do(func() {
		file_evolve_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_evolve_v1_event_proto_rawDesc), len(file_evolve_v1_event_proto_rawDesc)))
	})
	return file_evolve_v1_event_proto_rawDescData
}

var file_evolve_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_evolve_v1_event_proto_goTypes = []any{
	(*Event)(nil), // 0: evolve.v1.Event
}
var file_evolve_v1_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_evolve_v1_event_proto_init() }
func file_evolve_v1_event_proto_init() {
	if File_evolve_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_evolve_v1_event_proto_rawDesc), len(file_evolve_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_evolve_v1_event_proto_goTypes,
		DependencyIndexes: file_evolve_v1_event_proto_depIdxs,
		MessageInfos:      file_evolve_v1_event_proto_msgTypes,
	}.Build()
	File_evolve_v1_event_proto = out.File
	file_evolve_v1_event_proto_goTypes = nil
	file_evolve_v1_event_proto_depIdxs = nil
}
