{{- if not .Values.secret.existingName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order.fullname" . }}-secret
  labels:
    {{- include "order.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
{{- end }}
