{{- if not .Values.secret.existingName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudops.fullname" . }}-secret
  labels:
    {{- include "cloudops.labels" . | nindent 4 }}
type: Opaque
stringData:
  ALERT_WEBHOOK_TOKEN: {{ .Values.secret.alertWebhookToken | quote }}
{{- end }}
